inputs_def:
  - handle: analysed_dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: latex_render
    json_schema:
      enum:
        - mathml
        - svg
        - clipping
      ui:options:
        labels:
          - MathML
          - SVG
          - Clipping
    value: clipping
  - handle: table_render
    json_schema:
      enum:
        - html
        - clipping
      ui:options:
        labels:
          - HTML
          - Clipping
    value: clipping
  - handle: epub_file_path
    json_schema:
      type: string
      ui:widget: save
    value:
    nullable: true
outputs_def:
  - handle: epub_file_path
    description: Output
    json_schema:
      type: string
      ui:widget: save
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Generate EPUB
icon: ":twemoji:blue-book:"
