inputs_def:
  - handle: analysed_dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: epub_file_path
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: EPUB
            extensions:
              - epub
    value:
    nullable: true
  - group: render
    collapsed: false
  - handle: latex
    json_schema:
      type: boolean
    value: true
  - handle: table
    json_schema:
      type: boolean
    value: true
outputs_def:
  - handle: epub_file_path
    description: Output
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: EPUB
            extensions:
              - epub
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Generate EPUB
icon: ":twemoji:blue-book:"
