inputs_def:
  - handle: pdf
    description: Input
    json_schema:
      type: string
      ui:widget: file
    nullable: false
  - handle: device
    json_schema:
      enum:
        - cpu
        - cuda
        - cloud
      ui:options:
        labels:
          - CPU
          - CUDA
          - Cloud
    value: cloud
    nullable: false
  - handle: model_dir
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - handle: ocr_level
    json_schema:
      enum:
        - once
        - once_per_layout
      ui:options:
        labels:
          - Once
          - Once per Layout
    value: once
    nullable: false
  - handle: correction
    json_schema:
      enum:
        - off
        - once
        - detailed
      ui:options:
        labels:
          - Off
          - Once
          - Detailed
    value: once
  - handle: extract_formula
    json_schema:
      type: boolean
    value: false
  - handle: extract_table
    json_schema:
      type: boolean
    value: false
  - handle: window_tokens
    json_schema:
      type: integer
    value:
    nullable: true
  - handle: threads_count
    json_schema:
      type: integer
      minimum: 1
    value: 1
  - handle: retry_times
    json_schema:
      type: integer
      minimum: 0
    value: 5
    nullable: false
  - handle: retry_interval_seconds
    json_schema:
      type: number
      minimum: 0
    value: 1.5
    nullable: false
  - handle: output_dir
    json_schema:
      type: string
      ui:widget: dir
    nullable: true
  - handle: llm
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 1
      top_p: 0.8
      max_tokens: 4096
outputs_def:
  - handle: output_dir
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 575.9100785537335
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Analyse PDF
icon: ":fa6-solid:file-pdf:#F14C4C:"
