inputs_def:
  - handle: pdf
    description: Input
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: output_file
    json_schema:
      type: string
      ui:widget: save
    value:
    nullable: true
  - group: OCR
    collapsed: true
  - handle: device
    json_schema:
      enum:
        - cpu
        - cuda
        - cloud
      ui:options:
        labels:
          - CPU
          - CUDA
          - Cloud
    value: cloud
  - handle: ocr_level
    json_schema:
      enum:
        - once
        - once_per_layout
      ui:options:
        labels:
          - Once
          - Once per Layout
    value: once
  - handle: extract_formula
    json_schema:
      type: boolean
    value: false
  - handle: extract_table
    json_schema:
      type: boolean
    value: false
  - group: options
    collapsed: true
  - handle: assets_dir_name
    json_schema:
      type: string
    value: images
outputs_def:
  - handle: output_file
    description: Output
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: Markdown
            extensions:
              - md
              - markdown
              - mdown
ui:
  default_width: 411.70825911262096
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: PDF to Markdown
icon: ":twemoji:bookmark-tabs:"
