inputs_def:
  - handle: pdf
    description: Scanned PDF file to be converted
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: markdown
    description: MarkDown file save path, if not filled in, a default path will be specified
    json_schema:
      type: string
      ui:widget: save
    value:
    nullable: true
  - group: OCR
    collapsed: true
  - handle: device
    description: how to perform OCR, using CPU? using CUDA hardware acceleration? or
      uploading to the cloud?
    json_schema:
      enum:
        - cpu
        - cuda
        - cloud
      ui:options:
        labels:
          - CPU
          - CUDA
          - Cloud
    value: cloud
  - handle: ocr_level
    description: Should we perform OCR only once per page, or perform OCR multiple
      times to avoid missing some text?
    json_schema:
      enum:
        - once
        - once_per_layout
      ui:options:
        labels:
          - Once
          - Once per Layout
    value: once
  - group: options
    collapsed: true
  - handle: extract_formula
    description: Whether to extract formulas in the page. If enabled, the formulas
      will be parsed into LATEX format. If disabled, the formulas will be
      treated as static images.
    json_schema:
      type: boolean
    value: false
  - handle: extract_table
    description: Whether to extract the table in the page. If enabled, it will be
      recognized as HTML format, if disabled, it will be displayed as a static
      image.
    json_schema:
      type: boolean
    value: false
  - handle: assets_dir_name
    description: The name of the folder where the resource files such as images
      referenced by the markdown file are stored. Enter a relative address for
      the markdown file.
    json_schema:
      type: string
    value: images
outputs_def:
  - handle: saved_path
    description: Converted MarkDown file path.
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: Markdown
            extensions:
              - md
              - markdown
              - mdown
ui:
  default_width: 411.70825911262096
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: PDF to Markdown
icon: ":twemoji:bookmark-tabs:"
description: use OCR to recognize scanned PDF files and convert them into Markdown files.
